<a href="https://colab.research.google.com/github/JHWannabe/Python-AI_5/blob/main/0223%20Day5/4_%EC%8B%A0%EA%B2%BD%EB%A7%9D_%EA%B5%AC%EC%84%B1%EC%9A%94%EC%86%8C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Linear Layer**

* 신경망의 가장 기본 구성요소
* Fully-Connected(FC) Layer라고 불리기도 함
* 내부 파라미터에 따른 선형 변환을 수행하는 함수

# **2. Linear Layer 작동 방식**

* 각 입력 노드들에 weight(가중치)를 곱하고 모두 합친 뒤, bias(편향)을 더함
* 행렬곱으로 구현이 가능
* n차원에서 m차원으로 선형 변환 함수
* 이 함수의 파라미터를 조절하면 주어진 입력에 대해 원하는 출력을 만들 수 있음

In [1]:
import torch

In [2]:
x = torch.FloatTensor([[1, 2],
                       [3, 4],
                       [5, 6]])
y = torch.FloatTensor([[1, 2],
                       [1, 2]])
print(x.size(), y.size())

torch.Size([3, 2]) torch.Size([2, 2])


In [3]:
z = torch.matmul(x, y)
print(z.size())

torch.Size([3, 2])


In [4]:
W = torch.FloatTensor([[1, 2],
                       [3, 4],
                       [5, 6]])
b = torch.FloatTensor([2, 2])

In [5]:
print(W.size())
print(b.size())

torch.Size([3, 2])
torch.Size([2])


In [6]:
def linear(x, W, b):
  y = torch.matmul(x, W) + b
  return y

In [7]:
x = torch.FloatTensor([[1, 1, 1],
                       [2, 2, 2],
                       [3, 3, 3],
                       [4, 4, 4]])
print(x.size())

torch.Size([4, 3])


In [8]:
y = linear(x, W, b)
print(y.size())

torch.Size([4, 2])


# **3. nn.Module**

* nn 만들 때 상속받아서 사용하는 추상 클래스 (nn은 neural network)

In [9]:
import torch.nn as nn

In [10]:
class MyLinear(nn.Module):
  def __init__(self, input_dim=3, output_dim=2):
    self.input_dim = input_dim
    self.output_dim = output_dim

    super().__init__()
    
    self.W = torch.FloatTensor(input_dim, output_dim)
    self.b = torch.FloatTensor(output_dim)

  def forward(self, x):
    y = torch.matmul(x, self.W) + self.output_dim
    return y

In [11]:
linear = MyLinear(3, 2)
y = linear(x)

In [12]:
print(y.size())

torch.Size([4, 2])


# **4. nn.Parameter**

* 신경망 파라미터를 optimizer에 전달해 줄 때 사용
```
optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.9)
```

In [13]:
class MyLinear(nn.Module):
  def __init__(self, input_dim=3, output_dim=2):
    self.input_dim = input_dim
    self.output_dim = output_dim

    super().__init__()
    
    self.W = nn.Parameter(torch.FloatTensor(input_dim, output_dim))
    self.b = nn.Parameter(torch.FloatTensor(output_dim))

  def forward(self, x):
    y = torch.matmul(x, self.W) + self.output_dim
    return y

In [14]:
linear = MyLinear(3, 2)
y = linear(x)

In [15]:
print(y.size())

torch.Size([4, 2])


In [16]:
for p in linear.parameters():
  print(p)

Parameter containing:
tensor([[3.5246e+02, 3.0665e-41],
        [3.3631e-44, 0.0000e+00],
        [       nan, 3.8000e+01]], requires_grad=True)
Parameter containing:
tensor([3.5246e+02, 3.0665e-41], requires_grad=True)


# **5. nn.Linear를 통해 재구현**

In [17]:
class MyLinear(nn.Module):
  def __init__(self, input_dim=3, output_dim=2):
    self.input_dim = input_dim
    self.output_dim = output_dim

    super().__init__()
    
    self.linear = nn.Linear(input_dim, output_dim)

  def forward(self, x):
    y = self.linear(x)
    return y

In [18]:
linear = MyLinear(3, 2)
y = linear(x)
print(y.size())

torch.Size([4, 2])


In [19]:
for p in linear.parameters():
  print(p)

Parameter containing:
tensor([[ 0.3161,  0.1374,  0.2873],
        [ 0.2500,  0.5570, -0.5129]], requires_grad=True)
Parameter containing:
tensor([0.1467, 0.0965], requires_grad=True)
