<a href="https://colab.research.google.com/github/JHWannabe/Python-AI_5/blob/main/0223%20Day5/6_GPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1.GPU란?**

* GPU(Graphic Processing Unit)는 그래픽 처리, 특히 3D 모델링을 위한 프로세서로 탄생
* 다량의 병렬연산이 필요한 3D 랜더링, 딥러닝, 블록체인 등에 연산을 가속해주기 위해 사용

# **2. GPU 사용하는 방법**

In [1]:
import torch
import torch.nn as nn

In [2]:
x = torch.cuda.FloatTensor(2, 2)
print(x)
# No CUDA GPUs are available
# 에러가 발생할 경우 런타임 유형변경에서 GPU를 선택
# GPU가 여러개 있는 경우 GPU 번호를 확인
# 같은 디바이스에 있는 텐서끼리만 연산이 가능

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')


In [3]:
x = torch.FloatTensor(2, 2)
print(x)

tensor([[9.8786e+20, 3.0792e-41],
        [0.0000e+00, 0.0000e+00]])


In [4]:
# GPU로 보냄
x.cuda()

tensor([[9.8786e+20, 3.0792e-41],
        [0.0000e+00, 0.0000e+00]], device='cuda:0')

In [5]:
# GPU0으로 지정
d = torch.device('cuda:0')

In [6]:
# move가 아니라 copy로 됨
x.cuda(device=d)

tensor([[9.8786e+20, 3.0792e-41],
        [0.0000e+00, 0.0000e+00]], device='cuda:0')

In [7]:
x.device

device(type='cpu')

In [8]:
x = torch.cuda.FloatTensor(2, 2)

In [9]:
x = x.cpu()

In [10]:
d = torch.device('cpu')
x = x.to(d)

In [11]:
def print_params(model):
  for p in model.parameters():
    print(p)

In [12]:
linear = nn.Linear(2, 2)
print_params(linear)

Parameter containing:
tensor([[ 0.6902,  0.4979],
        [-0.4678,  0.3120]], requires_grad=True)
Parameter containing:
tensor([0.1519, 0.0917], requires_grad=True)


In [13]:
d = torch.device('cuda:0')
linear = linear.to(d)
print_params(linear)

Parameter containing:
tensor([[ 0.6902,  0.4979],
        [-0.4678,  0.3120]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([0.1519, 0.0917], device='cuda:0', requires_grad=True)


In [14]:
linear.device # 모델은 device attribute를 제공하지 않음

AttributeError: ignored

In [15]:
x = torch.cuda.FloatTensor(2, 2)

In [16]:
x.new(2, 2) # x와 같은 타입이면서 같은 디바이스에 있는 텐서를 만듬

tensor([[3.6893e+19, 1.4334e+00],
        [4.6780e-01, 3.1204e-01]], device='cuda:0')

In [17]:
torch.zeros_like(x)

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [18]:
torch.ones_like(x)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [19]:
list(linear.parameters())[0].new(2, 2)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

> 다른 device에 있는 텐서끼리는 연산할 수 없음